Repository fastai/fastai, pull requests merged in 2021-05, with the labels that each got.

#3124 Timedistributed layer and Image Sequence Tutorial
  fastai/_nbdev.py
  fastai/layers.py
  nbs/01_layers.ipynb
  nbs/24_tutorial.image_sequence.ipynb
Labels: enhancement

#3347 Make TTA turn shuffle and drop_last off when using ds_idx
  fastai/learner.py
  nbs/13a_learner.ipynb
Labels: bug

#3326 sort Perplexity with NLP metrics
  fastai/_nbdev.py
  fastai/metrics.py
  nbs/13b_metrics.ipynb
Labels: documentation
